version: 2.1
orbs:
  node: circleci/node@5.2.0
jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Build CSS
          command: yarn sass
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Build app
          command: yarn build
workflows:
  build-and-test:
    jobs:
      - build-and-test
